swagger: '2.0'
info:
  title: Job Board API
  version: 1.0.0

paths:
  /:
    get:
      summary: Health checker route
      description: Route to indicate whether the API is working
      produces:
        - application/json
      responses:
        200:
          description: OK
        500:
          description: Server Error
  /jobs:
    get:
      summary: Fetchs all jobs
      description: Fetches all information for jobs
      produces:
        - application/json
      responses:
        200:
          description: OK
  /jobs/{jobId}:
    get:
      summary: Fetches job by ID
      description: Fethcing all information relating to a specific job
      parameters:
        - in: path
          name: jobId
          required: true
          type: string
          description: UUID representing job.
      produces:
        - application/json
      responses:
        200:
          description: OK
